### ISSUE TITLE
Should boolean variable names also end in '?' just like boolean returning predicate functions?

### ISSUE THREAD

**Issue by anoopemacs** [bbatsov/clojure-style-guide#261]

**Comment by seancorfield** [comment]
I don't think there's much consensus on this. Some people like to use `?` to indicate a symbol that is bound to a Boolean, but a lot of people feel it should only be used for predicate functions.

I'm in the latter camp -- we have `!` and `*` (and `?`) for functions fairly commonly, meaning "mutates"(not safe in a transaction), "implementation" (often for the non-caching version of some fn or for the implementation fn of a macro) -- but we don't use any similar notations for local bindings. The only fairly common Var-level (non-function) annotation we tend to use is earmuffs `*some-dynamic-var*` and that's partly because that used to be required.

**Comment by bbatsov** [comment]
> I'm in the latter camp -- we have ! and * (and ?) for functions fairly commonly, meaning "mutates"(not safe in a transaction), "implementation" (often for the non-caching version of some fn or for the implementation fn of a macro) -- but we don't use any similar notations for local bindings. The only fairly common Var-level (non-function) annotation we tend to use is earmuffs *some-dynamic-var* and that's partly because that used to be required.

Same sentiment here. I'll also mention that's the prevailing practice in other lisps as well, based on my observations in the realms of a few other dialects.
