### ISSUE TITLE
Indenting cond

### ISSUE THREAD

**Issue by jeremyheiler** [bbatsov/clojure-style-guide#75]
The indentation for `cond` in the guide uses two spaces, but clojure-mode enforces one space. Given that clojure-mode is actively used, should we update the guide?

**Comment by nashbridges** [comment]
Now https://github.com/bbatsov/clojure-style-guide#one-space-indent rule is quite confusing for me as a clojure novice.

What is the difference between `or/and` and `cond`? clojure-emacs discussion ended up in

> Lists get a single space indent unless it's a known macro form, in which case it gets two?

Isn't `or` well known?

**Comment by bitti** [comment]
@nashbridges it's not about whether or not a macro is well known, but about if the macros is taking a body form (which is indented by 2 spaces, and not aligned with preceding arguments, e.g. bindings). Many of these macros are well known, but don't have to be. E.g. you can write your own macros which take body forms which should be indented accordingly. The macros `or` and `and` don't take body forms and are therefore formatted like normal functions.

`cond` is controversial since it objectively doesn't take a body form but a list of clauses. But since this list can get quite long it kind of feels like a body form.
